# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"make_batches": "kernel.ipynb",
         "sparsify": "kernel.ipynb",
         "sim_matrix_to_idx_and_score": "kernel.ipynb",
         "cosine_similarity": "kernel.ipynb",
         "cosine_distance": "kernel.ipynb",
         "hstack": "kernel.ipynb",
         "vstack": "kernel.ipynb",
         "stack": "kernel.ipynb",
         "RobustEncoder": "kernel.ipynb",
         "EstimatorKernel": "kernel.ipynb",
         "ForestKernel": "kernel.ipynb",
         "CategoricalKernel": "kernel.ipynb"}

modules = ["kernel.py"]

doc_url = "https://AlanGanem.github.io/heartwood/"

git_url = "https://github.com/AlanGanem/heartwood/tree/master/"

def custom_doc_links(name): return None
